## Homework № 1

In [17]:
# Exersize 1
import numpy as np
a = np.array([1, 6, 2, 8, 3, 11, 3, 10, 1, 7])
a.resize (5, 2)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [19]:
# Exersize 2
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [44]:
# Exersize 3
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [56]:
a1 = np.array ([a_centered[0][0], a_centered[1][0], a_centered[2][0], a_centered[3][0], a_centered[4][0]])
a2 = np.array ([a_centered[0][1], a_centered[1][1], a_centered[2][1], a_centered[3][1], a_centered[4][1]])
a_centered_sp = a1@a2
print(a_centered_sp)
N = a_centered.shape[0]
b = a_centered_sp / (N-1)
b

8.0


2.0

In [68]:
# Exersize 4
print(a)
np.cov(a.transpose(), bias = True)


[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


array([[0.8 , 1.6 ],
       [1.6 , 3.44]])

#Pandas


In [4]:
# Exersize 1
import pandas as pd
import numpy as np
lst = {'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}
authors = pd.DataFrame(lst)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [5]:
lst1 = {'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],\
       'price':[450, 300, 350, 500, 450, 370, 290]}
book = pd.DataFrame(lst1)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [6]:
# Exersize 2
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price


author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [7]:
# Exersize 3
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [8]:
# Exersize 4 

In [19]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})
print(authors_stat)

                price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000
